#!/usr/bin/perl

use strict; use warnings; use autodie;

my %repl = (
  "C1a"	 =>  "carolinus01",
  "C8a"	 =>  "carolinus02",
  "C9a"	 =>  "carolinus03",
  "C10a" =>  "carolinus04",
  "FL2a" =>  "carolinus05",
  "FL4a" =>  "carolinus06",
  "H2a"   =>  "aurifrons01",	
  "H3a"   =>  "aurifrons02",	
  "H4a"   =>  "aurifrons03",	
  "H5a"   =>  "aurirons04",	
  "KU1a"   =>  "pygmaeus01",	
  "KU2a"   =>  "dubius01",	
  "KU3a"   =>  "dubius02",	
  "KU4a"   =>  "santacruzi01",	
  "KU5a"   =>  "santacruzi_hoffmanni01",	
  "KU6a"   =>  "santacruzi02",	
  "KU7a"   =>  "santacruzi03",	
  "KU9a"   =>  "santacruzi04",	
  "KU11a"   =>  "dubius03",	
  "KU12a"   =>  "santacruzi05",	
  "KU14a"   =>  "santacruzi06",	
  "KU16a"   =>  "pygmaeus02",	
  "KU33a"   =>  "polygrammus01",	
  "KU34a"   =>  "polygrammus02",	
  "MJM1a"   =>  "carolinus07",	
  "MJM2a"   =>  "carolinus08",	
  "MJM3a"   =>  "carolinus09",	
  "MJM4a"   =>  "carolinus10",	
  "MJM5a"   =>  "carolinus11",	
  "MJM11a"   =>  "carolinus12",
  "MJM12a"   =>  "carolinus13",
  "MJM13a"   =>  "carolinus14",
  "MJM15a"   =>  "carolinus15",
  "MJM16a"   =>  "carolinus16",
  "MJM17a"   =>  "carolinus17",
  "MJM18a"   =>  "carolinus18",
  "MJM19a"   =>  "carolinus19",
  "SM29a"   =>  "contact_carolinus01",	
  "SM30a"   =>  "contact_carolinus02",	
  "SN1a"   =>  "aurifrons05",	
  "SN2a"   =>  "aurifrons06",	
  "SN3a"   =>  "aurifrons07",	
  "SN4a"   =>  "aurifrons08",	
  "SN5a"   =>  "aurifrons09",	
  "SN6a"   =>  "aurifrons10",	
  "SN7a"   =>  "aurifrons11",	
  "SN8a"   =>  "aurifrons12",	
  "SN9a"   =>  "aurifrons13",	
  "SN10a"   =>  "aurifrons14",	
  "SN11a"   =>  "contact_aurifrons01",	
  "SN13a"   =>  "contact_aurifrons02",	
  "SN14a"   =>  "contact_aurifrons03",	
  "SN15a"   =>  "contact_aurifrons04",	
  "SN16a"   =>  "contact_aurifrons05",	
  "SN17a"   =>  "contact_aurifrons06",	
  "SN18a"   =>  "contact_aurifrons07",	
  "SN19a"   =>  "contact_aurifrons08",	
  "SN21a"   =>  "contact_aurifrons09",	
  "SN22a"   =>  "contact_carolinus03",	
  "SN23a"   =>  "contact_carolinus04",	
  "SN24a"   =>  "contact_carolinus05",	
  "SN25a"   =>  "contact_carolinus06",	
  "SN26a"   =>  "contact_carolinus07",	
  "SN27a"   =>  "contact_carolinus08",	
  "SN28a"   =>  "contact_carolinus09",	
  "SN31a"   =>  "contact_aurifrons10",	
  "SN32a"   =>  "contact_carolinus10",	
  "SN33a"   =>  "carolinus20",	
  "SN34a"   =>  "contact_aurifrons11",	
  "SN35a"   =>  "contact_carolinus11",	
  "SN36a"   =>  "contact_aurifrons12",	
  "SN37a"   =>  "contact_carolinus12",	
  "SNMB171a"   =>  "carolinus21",
  "UW1a"   =>  "pucherani01",	
  "UW2a"   =>  "hoffmannii01",	
  "UW3a"   =>  "hoffmannii02",	
  "UW4a"   =>  "hoffmannii03",	
  "UW5a"   =>  "hoffmannii04",	
  "UW6a"   =>  "hoffmannii05",	
  "UW7a"   =>  "hoffmannii06",	
  "UW8a"   =>  "hoffmannii07",	
  "UW9a"   =>  "carolinus22",	
  "UW12a"   =>  "uropygialis01",	
  "UW13a"   =>  "formicivorus01",	
  "UW14a"   =>  "chrysogenys01",	
  "UW15a"   =>  "uropygialis02",	
  "UW16a"   =>  "uropygialis03",	
  "UW17a"   =>  "polygrammus03",	
  "UW20a"   =>  "santacruzi07",	
  "UW21a"   =>  "santacruzi08",	
  "UW22a"   =>  "santacruzi09",	
  "UW25a"   =>  "pygmaeus03",	
  "UW26a"   =>  "pygmaeus04",	
  "UW27a"   =>  "pygmaeus05",	
  "UW28a"   =>  "veraecrucis01",	
  "UW30a"   =>  "veraecrucis02",	
  "UW31a"   =>  "pucherani02",	
  "UW32a"   =>  "polygrammus04",	
  "UW35a"   =>  "pygmaeus06",	
  "UW36a"   =>  "chrysogenys02",	
  "UW37a"   =>  "rubricapillus01",	
  "UW39a"   =>  "rubricapillus02",	
  "UW40a"   =>  "santacruzi10",	
  "UW41a"   =>  "santacruzi11",	
  "UW42a"   =>  "santacruzi12",	


);

open( my $F, '<', "input.txt" );
open( my $OUTPUT, '>', "output.txt" );

while ( <$F> ) {
  foreach my $key ( sort keys %repl ) {
     s/\b$key\b/$repl{$key}/g;
  }
  print $OUTPUT $_; 
}

close( $F );
close( $OUTPUT );